### ISSUE TITLE
vllm部署失败，cuda out of memory

### ISSUE THREAD

**Issue by MLrookie** [zjunlp/KnowLM#106]
按照教程运行，也把vllm版本降到0.1.1了，模型加载报错，cuda out of memory,

模型是knowlm-13b-ie，GPU A6000, 50G显存

报错内容：
```
Init model
2024-01-09 16:04:55,716 WARNING worker.py:1395 -- SIGTERM handler is not set because current thread is not the main thread.
INFO:     Started server process [1560933]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
2024-01-09 16:05:01,012 INFO worker.py:1724 -- Started a local Ray instance.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
(Worker pid=1566571) [W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
{'instruction': '你好', 'input': '', 'parameters': {'top_p': 0.7, 'max_tokens': 256}}
progress sent_to_model=1 recv_from_model=0
(Worker pid=1566571) /data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/vllm/worker/worker.py:218: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(Worker pid=1566571)   tokens_tensor = torch.cuda.LongTensor(input_tokens)
(Worker pid=1566572) [W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/lxw/project/KnowLM/inference/launch_vllm.py", line 73, in _thread
    server = self.init_model(self.vllm_args)
  File "/data1/lxw/project/KnowLM/inference/launch_vllm.py", line 130, in init_model
    server = LLMEngine.from_engine_args(server_args)
  File "/data1/lxw/project/KnowLM/inference/llm_engine.py", line 171, in from_engine_args
    engine = cls(*engine_configs, distributed_init_method, devices,
  File "/data1/lxw/project/KnowLM/inference/llm_engine.py", line 122, in __init__
    self._init_cache()
  File "/data1/lxw/project/KnowLM/inference/llm_engine.py", line 160, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/data1/lxw/project/KnowLM/inference/llm_engine.py", line 340, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OutOfMemoryError): ray::Worker.init_cache_engine() (pid=1566571, ip=192.168.8.3, actor_id=863313ffc524d7e0a42bddbc01000000, repr=<vllm.worker.worker.Worker object at 0x7f14640b6610>)
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/vllm/worker/worker.py", line 126, in init_cache_engine
    self.cache_engine = CacheEngine(
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/vllm/worker/cache_engine.py", line 40, in __init__
    self.gpu_cache = self.allocate_gpu_cache()
  File "/data1/lxw/miniconda3/envs/knowlm/lib/python3.9/site-packages/vllm/worker/cache_engine.py", line 76, in allocate_gpu_cache
    value_blocks = torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 382.00 MiB. GPU 0 has a total capacty of 47.54 GiB of which 377.88 MiB is free. Process 32339 has 318.00 MiB memory in use. Process 1381278 has 2.69 GiB memory in use. Process 113194 has 12.72 GiB memory in use. Including non-PyTorch memory, this process has 31.43 GiB memory in use. Of the allocated memory 29.89 GiB is allocated by PyTorch, and 91.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-01-09 16:23:55,990 E 1560933 1561602] gcs_rpc_client.h:552: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.
```

没看到有打印“Model ready”，请问是什么原因呢？

**Comment by MikeDean2367** [comment]
您好，目前的最新版本为`0.2.7`，我们现有的环境无法安装`0.1.2`版本的vllm，正在适配最新版本的`vllm`。下面是针对您目前情况的一些可能的解决办法：
1. 教程中提到的`vllm`的版本为`0.1.2`，而不是`0.1.1`
2. 您可以尝试将模型使用`fp16`或者`bf16`进行加载
3. 尝试使用更小的模型，比如llama-7b-chat等，来排除是硬件导致的问题

**Comment by MLrookie** [comment]
我找到原因了，好像多卡部署的时候会有问题，切换成单卡就可以了
