### ISSUE TITLE
求助：由于在国内使用阿里云服务器，无法科学上网接入huggingface下载模型，通过魔塔下载好模型后运行，代码有报错

### ISSUE THREAD

**Issue by YINING8888** [zjunlp/KnowLM#127]
报错内容如下，感谢帮助
/mnt/workspace/KnowLM> python examples/generate_lora.py --base_model /mnt/workspace/knowlm-13b-zhixi --run_ie_cases
testing ie ablities!
load_8bit=False
Traceback (most recent call last):
  File "/mnt/workspace/KnowLM/examples/generate_lora.py", line 232, in <module>
    fire.Fire(main)
  File "/home/pai/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/KnowLM/examples/generate_lora.py", line 131, in main
    model = LlamaForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaForCausalLM.__init__() got an unexpected keyword argument 'load_in_4bit'

**Comment by MikeDean2367** [comment]
您好，请问您使用的transformers的版本是多少，建议尝试使用最新的transformers包。如有问题请告知我 :)

**Comment by YINING8888** [comment]
您好，非常感谢您的帮助。程序能够正常运行了。但是cuda显示超出内存了，请问需要多大的内存来运行这个程序呢

**Comment by MikeDean2367** [comment]
26GB左右

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by YINING8888** [comment]
非常感谢你的回答，问题已经解决了
