### ISSUE TITLE
lora微调为什么会出现RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by xiang-hui744** [zjunlp/KnowLM#138]
File "/home/keke/KnowLM/finetune/lora/knowlm/finetune.py", line 299, in <module>
    fire.Fire(train)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/keke/KnowLM/finetune/lora/knowlm/finetune.py", line 289, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/trainer.py", line 2006, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/trainer.py", line 2287, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/trainer.py", line 2993, in evaluate
    output = eval_loop(
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/trainer.py", line 3234, in evaluation_loop
    losses = nested_numpify(losses_host)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/trainer_pt_utils.py", line 160, in nested_numpify
    return t.numpy()
RuntimeError: Numpy is not available

  7%|▋         | 10/145 [55:46<12:32:55, 334.63s/it]

                                               [ATraceback (most recent call last):
  File "/home/keke/anaconda3/envs/knowlm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/keke/anaconda3/envs/knowlm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/keke/anaconda3/envs/knowlm/bin/python', 'finetune.py', '--data_path', './data/introduction_train.json', '--base_model', '/home/keke/KnowLM/knowlm-13b-zhixi']' returned non-zero exit status 1.

**Comment by xiang-hui744** [comment]
numpy的版本问题
