### ISSUE TITLE
从checkpoint继续lora微调报错

### ISSUE THREAD

**Issue by xiang-hui744** [zjunlp/KnowLM#140]
使用命令：
`CUDA_VISIBLE_DEVICES=0 accelerate launch finetune.py --data_path ./data/introduction2_train.json --base_model /home/keke/KnowLM/knowlm-13b-zhixi --resume_from_checkpoint /home/keke/KnowLM/finetune/lora/knowlm/checkpoint/in22/checkpoint-130
`
报错：
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:25<00:00,  8.47s/it]
/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/peft/utils/other.py:122: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
Restarting from /home/keke/KnowLM/finetune/lora/knowlm/checkpoint/in22/checkpoint-130/pytorch_model.bin
Traceback (most recent call last):
  File "/home/keke/KnowLM/finetune/lora/knowlm/finetune.py", line 301, in <module>
    fire.Fire(train)
  File "/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/keke/KnowLM/finetune/lora/knowlm/finetune.py", line 217, in train
    model.print_trainable_parameters()  # Be more transparent about the % of trainable params.
AttributeError: '_IncompatibleKeys' object has no attribute 'print_trainable_parameters'
Traceback (most recent call last):
  File "/home/keke/anaconda3/envs/lora/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/keke/anaconda3/envs/lora/lib/python3.9/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/keke/anaconda3/envs/lora/bin/python', 'finetune.py', '--data_path', './data/introduction2_train.json', '--base_model', '/home/keke/KnowLM/knowlm-13b-zhixi', '--resume_from_checkpoint', '/home/keke/KnowLM/finetune/lora/knowlm/checkpoint/in22/checkpoint-130']' returned non-zero exit status 1.

**Comment by MikeDean2367** [comment]
您好，请尝试注释[这一行代码](https://github.com/zjunlp/KnowLM/blob/e8edd79a0355aec9c421900b466a429a5376fa74/finetune/lora/knowlm/finetune.py#L212)

**Comment by xiang-hui744** [comment]
> 您好，请尝试注释[这一行代码]
我发现是model在load_state_dict以后变成_IncompatibleKeys(missing_keys=['base_model.model.model.embed_tokens.weight', 'base_model.model.model.layers.0.self_attn.q_proj.weight', 'base_model.model.model.layers.0.self_attn.k_proj.weight', 'base_model.model.model.layers.0.self_attn.v_proj.weight', 'base_model.model.model.layers.0.self_attn.o_proj.weight', ...])
导致加载参数一直报错，不知道如何解决，请指教！
<img width="1180" alt="image" src="https://github.com/zjunlp/KnowLM/assets/57001862/25aa31e9-2065-4c12-b725-de8f25cf89eb">

**Comment by MikeDean2367** [comment]
您好，参考这个[issue](https://github.com/huggingface/peft/issues/285)，建议使用最新版本的peft，如仍有问题，请告知我，并提供相应的包的版本号 :)

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by xiang-hui744** [comment]
> 您好，参考这个[issue](https://github.com/huggingface/peft/issues/285)，建议使用最新版本的peft，如仍有问题，请告知我，并提供相应的包的版本号 :)



> 您好，参考这个[issue](https://github.com/huggingface/peft/issues/285)，建议使用最新版本的peft，如仍有问题，请告知我，并提供相应的包的版本号 :)



> 您好，参考这个[issue](https://github.com/huggingface/peft/issues/285)，建议使用最新版本的peft，如仍有问题，请告知我，并提供相应的包的版本号 :)

更新以后仍然报错，包版本号如下：
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.31.0                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
bitsandbytes              0.37.2                   pypi_0    pypi
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2024.6.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.20.0                   pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
email-validator           2.2.0                    pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
fastapi                   0.111.0                  pypi_0    pypi
fastapi-cli               0.0.4                    pypi_0    pypi
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fire                      0.6.0                    pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.5.0                 pypi_0    pypi
gradio                    4.37.1                   pypi_0    pypi
gradio-client             1.0.2                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.23.4                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jsonschema                4.22.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     2.0.0                    pypi_0    pypi
openssl                   3.0.14               h5eee18b_0  
orjson                    3.10.5                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
peft                      0.11.2.dev0              pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0             py39h06a4308_0  
psutil                    6.0.0                    pypi_0    pypi
pyarrow                   16.1.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pydantic                  2.7.4                    pypi_0    pypi
pydantic-core             2.18.4                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.9.19               h955ad1f_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.18.1                   pypi_0    pypi
ruff                      0.4.10                   pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                69.5.1           py39h06a4308_0  
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
starlette                 0.37.2                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.13.3                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torch                     1.13.1+cu116             pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.28.1                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
ujson                     5.10.0                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
uvicorn                   0.30.1                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
watchfiles                0.22.0                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0  
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  

**报错如下：**
Traceback (most recent call last):  File "/home/keke/KnowLM/finetune/lora/knowlm/finetune.py", line 16, in <module>
    from peft import (
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/mapping.py", line 23, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/mixed_model.py", line 26, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/tuners/__init__.py", line 22, in <module>
    from .loha import LoHaConfig, LoHaModel
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/tuners/loha/__init__.py", line 16, in <module>
    from .layer import Conv2d, Linear, LoHaLayer
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/tuners/loha/layer.py", line 296, in <module>
    class HadaWeight(torch.autograd.Function):
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/tuners/loha/layer.py", line 298, in HadaWeight
    def forward(ctx, w1a, w1b, w2a, w2b, scale=torch.tensor(1)):
/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/tuners/loha/layer.py:298: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:77.)
  def forward(ctx, w1a, w1b, w2a, w2b, scale=torch.tensor(1)):
Traceback (most recent call last):
  File "/home/keke/KnowLM/finetune/lora/knowlm/finetune.py", line 16, in <module>
    from peft import (
ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft' (/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/peft/__init__.py)
Traceback (most recent call last):
  File "/home/keke/anaconda3/envs/lora2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/keke/anaconda3/envs/lora2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/keke/anaconda3/envs/lora2/bin/python', 'finetune.py', '--data_path', './data/introduction2_train.json', '--base_model', '/home/keke/KnowLM/knowlm-13b-zhixi', '--resume_from_checkpoint', '/home/keke/KnowLM/finetune/lora/knowlm/checkpoint/in22/checkpoint-130']' returned non-zero exit status 1.

**Comment by xiang-hui744** [comment]
> > 您好，请尝试注释[这一行代码]
> > 我发现是model在load_state_dict以后变成_IncompatibleKeys(missing_keys=['base_model.model.model.embed_tokens.weight', 'base_model.model.model.layers.0.self_attn.q_proj.weight', 'base_model.model.model.layers.0.self_attn.k_proj.weight', 'base_model.model.model.layers.0.self_attn.v_proj.weight', 'base_model.model.model.layers.0.self_attn.o_proj.weight', ...])
> > 导致加载参数一直报错，不知道如何解决，请指教！
> 
> <img alt="image" width="1180" src="https://private-user-images.githubusercontent.com/57001862/342722585-25aa31e9-2065-4c12-b725-de8f25cf89eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTE3MTksIm5iZiI6MTcxOTM5MTQxOSwicGF0aCI6Ii81NzAwMTg2Mi8zNDI3MjI1ODUtMjVhYTMxZTktMjA2NS00YzEyLWI3MjUtZGU4ZjI1Y2Y4OWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4NDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MGY1ZTllM2I4NGM3NWQwN2I0ZDk2MDIyYjQ3ZDQ5NTE3Zjk2ZmZhOGE5ZDk2YTIzYzRlODk5YTBjNjQ1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjbNf3IhmQB0Y3bs7YcDXs0w97oLD-2yVWE0Gz59JRE">



> > 您好，请尝试注释[这一行代码]
> > 我发现是model在load_state_dict以后变成_IncompatibleKeys(missing_keys=['base_model.model.model.embed_tokens.weight', 'base_model.model.model.layers.0.self_attn.q_proj.weight', 'base_model.model.model.layers.0.self_attn.k_proj.weight', 'base_model.model.model.layers.0.self_attn.v_proj.weight', 'base_model.model.model.layers.0.self_attn.o_proj.weight', ...])
> > 导致加载参数一直报错，不知道如何解决，请指教！
> 
> <img alt="image" width="1180" src="https://private-user-images.githubusercontent.com/57001862/342722585-25aa31e9-2065-4c12-b725-de8f25cf89eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTE3MTksIm5iZiI6MTcxOTM5MTQxOSwicGF0aCI6Ii81NzAwMTg2Mi8zNDI3MjI1ODUtMjVhYTMxZTktMjA2NS00YzEyLWI3MjUtZGU4ZjI1Y2Y4OWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4NDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MGY1ZTllM2I4NGM3NWQwN2I0ZDk2MDIyYjQ3ZDQ5NTE3Zjk2ZmZhOGE5ZDk2YTIzYzRlODk5YTBjNjQ1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjbNf3IhmQB0Y3bs7YcDXs0w97oLD-2yVWE0Gz59JRE">



> > 您好，请尝试注释[这一行代码]
> > 我发现是model在load_state_dict以后变成_IncompatibleKeys(missing_keys=['base_model.model.model.embed_tokens.weight', 'base_model.model.model.layers.0.self_attn.q_proj.weight', 'base_model.model.model.layers.0.self_attn.k_proj.weight', 'base_model.model.model.layers.0.self_attn.v_proj.weight', 'base_model.model.model.layers.0.self_attn.o_proj.weight', ...])
> > 导致加载参数一直报错，不知道如何解决，请指教！
> 
> <img alt="image" width="1180" src="https://private-user-images.githubusercontent.com/57001862/342722585-25aa31e9-2065-4c12-b725-de8f25cf89eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTE3MTksIm5iZiI6MTcxOTM5MTQxOSwicGF0aCI6Ii81NzAwMTg2Mi8zNDI3MjI1ODUtMjVhYTMxZTktMjA2NS00YzEyLWI3MjUtZGU4ZjI1Y2Y4OWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4NDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MGY1ZTllM2I4NGM3NWQwN2I0ZDk2MDIyYjQ3ZDQ5NTE3Zjk2ZmZhOGE5ZDk2YTIzYzRlODk5YTBjNjQ1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjbNf3IhmQB0Y3bs7YcDXs0w97oLD-2yVWE0Gz59JRE">

这个模型导入错误对应的peft版本是0.5.0
