### ISSUE TITLE
ValueErrorValueError: : ValueErrorFound `optimizer` configured in the DeepSpeed config, but no `scheduler`.

### ISSUE THREAD

**Issue by GzmCR** [zjunlp/KnowLM#30]
你好，我们在跑pretrain的时候发现以下这个问题，是deepspeed版本的问题吗，请问你们训练时deepspeed的版本是多少
Traceback (most recent call last):
  File "/data1/gzm/cryptoGPT/train.py", line 181, in <module>
    train()
  File "/data1/gzm/cryptoGPT/train.py", line 175, in train
    trainer.train(resume_from_checkpoint=model_args.resume_path if model_args.resume_path != None else False)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1725, in _inner_training_loop
    self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 361, in deepspeed_init
Traceback (most recent call last):
  File "/data1/gzm/cryptoGPT/train.py", line 181, in <module>
    train()
  File "/data1/gzm/cryptoGPT/train.py", line 175, in train
    trainer.train(resume_from_checkpoint=model_args.resume_path if model_args.resume_path != None else False)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1725, in _inner_training_loop
Traceback (most recent call last):
  File "/data1/gzm/cryptoGPT/train.py", line 181, in <module>
    train()
  File "/data1/gzm/cryptoGPT/train.py", line 175, in train
    self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 361, in deepspeed_init
    trainer.train(resume_from_checkpoint=model_args.resume_path if model_args.resume_path != None else False)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
Traceback (most recent call last):
  File "/data1/gzm/cryptoGPT/train.py", line 181, in <module>
    return inner_training_loop(
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1725, in _inner_training_loop
    train()
  File "/data1/gzm/cryptoGPT/train.py", line 175, in train
    trainer.train(resume_from_checkpoint=model_args.resume_path if model_args.resume_path != None else False)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
    self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 361, in deepspeed_init
    return inner_training_loop(
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer.py", line 1725, in _inner_training_loop
    self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 361, in deepspeed_init
    optimizer, lr_scheduler = deepspeed_optim_sched(
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 307, in deepspeed_optim_sched
    optimizer, lr_scheduler = deepspeed_optim_sched(    
    optimizer, lr_scheduler = deepspeed_optim_sched(optimizer, lr_scheduler = deepspeed_optim_sched(

  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 307, in deepspeed_optim_sched
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 307, in deepspeed_optim_sched
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/deepspeed.py", line 307, in deepspeed_optim_sched
    raise ValueError(
ValueError: Found `optimizer` configured in the DeepSpeed config, but no `scheduler`. Please configure a scheduler in the DeepSpeed config.
        raise ValueError(raise ValueError(    

raise ValueError(
ValueErrorValueError: : ValueErrorFound `optimizer` configured in the DeepSpeed config, but no `scheduler`. Please configure a scheduler in the DeepSpeed config.Found `optimizer` configured in the DeepSpeed config, but no `scheduler`. Please configure a scheduler in the DeepSpeed config.: 

Found `optimizer` configured in the DeepSpeed config, but no `scheduler`. Please configure a scheduler in the DeepSpeed config.
[2023-06-28 20:07:32,516] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2594513
[2023-06-28 20:07:32,517] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2594514
[2023-06-28 20:07:32,907] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2594515
[2023-06-28 20:07:32,922] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2594516
[2023-06-28 20:07:32,931] [ERROR] [launch.py:321:sigkill_handler] ['/data/gzm/anaconda3/envs/cryptoGPT/bin/python3.9', '-u', 'train.py', '--local_rank=3', '--model_name_or_path', '../pretrain_model/llama-7b-huggyllama/', '--model_max_length', '1024', '--data_path', 'mydataset/undergraduate_program', '--output_dir', 'output', '--num_train_epochs', '1', '--per_device_train_batch_size', '1', '--per_device_eval_batch_size', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '100', '--save_total_limit', '1', '--learning_rate', '1.5e-5', '--warmup_steps', '300', '--logging_steps', '1', '--report_to', 'tensorboard', '--gradient_checkpointing', 'True', '--deepspeed', 'configs/config.json', '--fp16', 'True', '--log_on_each_node', 'False', '--lr_scheduler_type', 'cosine', '--adam_beta1', '0.9', '--adam_beta2', '0.95', '--weight_decay', '0.1'] exits with return code = 1

**Comment by GzmCR** [comment]
我们在config.json中加了个"scheduler"::{ "lr_scheduler_type":"cosine" }就不报这个错了，但是在后续运行过程中内存爆了，请问这个是正常情况吗？我们的机器是4*3090，120G内存，加载的LLama-7b模型，train和eval的batch_size都设成1了，训练数据只有2000多条。

**Comment by MikeDean2367** [comment]
您好，我们使用的deepspeed版本号为`0.8.3`，使用的transformers版本是`0.48.3`。
120GB的内存似乎不太够吧，因为使用的`ZeRO3`，需要较大的内存开销。您如果希望判断是否是内存大小不足的情况，您可以将`llama`的超参数降低（即不加载7B原始权重，可以更改llamaconfig，实例化一个较小的模型，比如降低模型层数、降低隐藏层维度等），观察是否是由于内存原因导致。如果您有进一步消息，欢迎讨论 :)

**Comment by GzmCR** [comment]
> 您好，我们使用的deepspeed版本号为`0.8.3`，使用的transformers版本是`0.48.3`。 120GB的内存似乎不太够吧，因为使用的`ZeRO3`，需要较大的内存开销。您如果希望判断是否是内存大小不足的情况，您可以将`llama`的超参数降低（即不加载7B原始权重，可以更改llamaconfig，实例化一个较小的模型，比如降低模型层数、降低隐藏层维度等），观察是否是由于内存原因导致。如果您有进一步消息，欢迎讨论 :)

非常感谢，确实是内存的问题，我们调下了模型参数可以训练了，但遇到以下的报错，应该是我们在config中加"scheduler"::{ "lr_scheduler_type":"cosine" }的问题，请问您知道是什么原因嘛。我们deepspeed版本是0.8.3，还有我们没找到0.48.3版本的transformers，我们transformers版本是4.30.2，不知道是不是transformers版本的原因
AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr'
    logs["learning_rate"] = self._get_learning_rate()
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/transformers/trainer_pt_utils.py", line 846, in _get_learning_rate
    last_lr = self.lr_scheduler.get_last_lr()[0]
  File "/data/gzm/anaconda3/envs/cryptoGPT/lib/python3.9/site-packages/accelerate/scheduler.py", line 86, in get_last_lr
    return self.scheduler.get_last_lr()
AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr'

**Comment by MikeDean2367** [comment]
您好，您可以参考一下这个[issue](https://github.com/huggingface/transformers/issues/24359)，个人感觉是transformers或者accelerate的版本问题。

**Comment by GzmCR** [comment]
> 您好，您可以参考一下这个[issue](https://github.com/huggingface/transformers/issues/24359)，个人感觉是transformers或者accelerate的版本问题。

非常感谢！确实是transformers版本的问题，我们将版本回退到4.29.2就可以正常运行了
