### ISSUE TITLE
请问如何使用modelscope调用zhixi13bfp16

### ISSUE THREAD

**Issue by ykallan** [zjunlp/KnowLM#32]
以下是我用modelscope加载的代码：
```python
# encoding: utf-8


from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks


pretrained_model = r"D:\nlp_about\pretrained_model\zhixi-13b-diff-fp16"

model = pipeline(task=Tasks.named_entity_recognition, model=pretrained_model)


text = "请在以下商品名称中提取出品牌，型号，通用名，商品名称。商品名称如下：得力 5561 风琴包 (单位：只) 黄&&得力556112格A6风琴包(计价单位：个)(24个/箱)"

result = model(text)
print(result)

```

以下是控制台输出：
```text
2023-07-03 21:24:03,015 - modelscope - INFO - PyTorch version 1.12.1+cu116 Found.
2023-07-03 21:24:03,018 - modelscope - INFO - TensorFlow version 2.10.1 Found.
2023-07-03 21:24:03,019 - modelscope - INFO - Loading ast index from C:\Users\k\.cache\modelscope\ast_indexer
2023-07-03 21:24:03,098 - modelscope - INFO - Loading done! Current index file version is 1.7.0, with md5 d39bc57dc459b309a41217cdd2100bcd and a total number of 861 components indexed
2023-07-03 21:24:03,819 - modelscope - WARNING - ('PIPELINES', 'named-entity-recognition', None) not found in ast index file
Traceback (most recent call last):
  File "D:\nlp_about\zhixi-13b-demo\main.py", line 10, in <module>
    model = pipeline(task=Tasks.named_entity_recognition, model=pretrained_model)
  File "C:\Users\k\.conda\envs\torch112\lib\site-packages\modelscope\pipelines\builder.py", line 147, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\k\.conda\envs\torch112\lib\site-packages\modelscope\pipelines\builder.py", line 59, in build_pipeline
    return build_from_cfg(
  File "C:\Users\k\.conda\envs\torch112\lib\site-packages\modelscope\utils\registry.py", line 206, in build_from_cfg
    raise TypeError(
TypeError: type must be a str or valid type, but got <class 'NoneType'>

Process finished with exit code 1

```

不太清楚应该怎样调用这个13b的模型，在网上也没找到对应的说明教程，modelscope网站也没有找到说明，不知道该如何处理了

**Comment by MikeDean2367** [comment]
您好，非常感谢您对我们工作的关注。
由于meta官方没有完全开放出LLaMA的权重，因此我们将ZhiXi的权重与LLaMA权重进行作差，Modelscope 上提供的也为差值模型，因此无法直接使用pipeline进行推理，它的使用需要按照我们提供的[使用说明](https://github.com/zjunlp/KnowLM/blob/main/tutorial-notebooks/tutorial.ipynb)。
