### ISSUE TITLE
合并lora参数错误

### ISSUE THREAD

**Issue by funs690** [zjunlp/KnowLM#45]
尝试使用脚本合并模型zhixi与lora参数出错，日志入下：

python tools/export_hf_checkpoint.py --base_model zhixi --lora_model lora --output_dir zhixi-lora

日志如下：
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/fzq/anaconda3/envs/zhixi/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [03:19<00:00, 33.32s/it]
Traceback (most recent call last):
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/peft_model.py", line 287, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PeftModelForCausalLM' object has no attribute 'merge_and_unload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/tuners/lora.py", line 204, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute 'merge_and_unload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fzq/source/KnowLM/tools/export_hf_checkpoint.py", line 60, in <module>
    main()
  File "/home/fzq/source/KnowLM/tools/export_hf_checkpoint.py", line 41, in main
    lora_model = lora_model.merge_and_unload()
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/peft_model.py", line 289, in __getattr__
    return getattr(self.base_model, name)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/tuners/lora.py", line 206, in __getattr__
    return getattr(self.model, name)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'

**Comment by Alexzhuan** [comment]
您好，

注意到您使用的是`tools/export_hf_checkpoint.py`，这里LoRA参数合并以README里提供的方式为准, [combining-zhixi-13b-lora-weights-with-zhixi-13b-weights](https://github.com/zjunlp/KnowLM/tree/main#26-combining-zhixi-13b-lora-weights-with-zhixi-13b-weights)。

**Comment by funs690** [comment]
python tools/weight_diff.py merge --path_zhixi ./zhixi --path_lora ./lora --path_sfted ./zhixi-sft
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [04:05<00:00, 41.00s/it]
Traceback (most recent call last):
  File "/home/fzq/source/KnowLM/tools/weight_diff.py", line 169, in <module>
    fire.Fire(main)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/fzq/source/KnowLM/tools/weight_diff.py", line 165, in main
    globals()[task](**kwargs)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/fzq/source/KnowLM/tools/weight_diff.py", line 149, in merge
    model_lora = PeftModel.from_pretrained(
NameError: name 'PeftModel' is not defined

还是一样的问题

**Comment by funs690** [comment]
还是一样的问题，依赖包缺失
tools/weight_diff.py 增加依赖包导入

line 21 add `from peft import PeftModel` 修正后出现新的错误

Traceback (most recent call last):
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/peft_model.py", line 287, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PeftModelForCausalLM' object has no attribute 'merge_and_unload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/tuners/lora.py", line 204, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute 'merge_and_unload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fzq/source/KnowLM/tools/weight_diff.py", line 170, in <module>
    fire.Fire(main)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/fzq/source/KnowLM/tools/weight_diff.py", line 166, in main
    globals()[task](**kwargs)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/fzq/source/KnowLM/tools/weight_diff.py", line 158, in merge
    model_sfted = model_lora.merge_and_unload()
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/peft_model.py", line 289, in __getattr__
    return getattr(self.base_model, name)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/peft/tuners/lora.py", line 206, in __getattr__
    return getattr(self.model, name)
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'

**Comment by zxlzr** [comment]
您好，我们正在抓紧排查参数合并部分的问题。

**Comment by funs690** [comment]
安装最新peft包，需要>0.2.0，建议使用最新版本
pip install git+https://github.com/huggingface/peft.git


依赖中需要更新下peft版本
