### ISSUE TITLE
Error：The current `device_map` had weights offloaded to the disk.

### ISSUE THREAD

**Issue by jia95812** [zjunlp/KnowLM#62]
when I use "python examples/generate_lora_web.py --base_model ./model/knowlm-13b-ie", it would create the error like this:
(knowlm) G:\KnowLM-main>python examples/generate_lora_web.py --base_model ./model/knowlm-13b-ie
Traceback (most recent call last):
  File "G:\KnowLM-main\examples\generate_lora_web.py", line 209, in <module>
    fire.Fire(main)
  File "D:\ProgramData\Anaconda3\envs\knowlm\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\ProgramData\Anaconda3\envs\knowlm\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\ProgramData\Anaconda3\envs\knowlm\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "G:\KnowLM-main\examples\generate_lora_web.py", line 42, in main
    model = LlamaForCausalLM.from_pretrained(
  File "D:\ProgramData\Anaconda3\envs\knowlm\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\ProgramData\Anaconda3\envs\knowlm\lib\site-packages\transformers\modeling_utils.py", line 2889, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by MikeDean2367** [comment]
您好，请问您的运行环境是什么呢，比如显存和内存大小。可以参考[此处](https://zhuanlan.zhihu.com/p/605640431)和[此处](https://github.com/nomic-ai/gpt4all/issues/239)。

**Comment by zxlzr** [comment]
Could please provide your GPU, and memory settings?

**Comment by jia95812** [comment]
2G的独显GPU，16G内存

**Comment by MikeDean2367** [comment]
建议更换大的显存或者内存，否则是无法运行的。
