### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Hubotcoder** [zjunlp/KnowLM#71]
Hello, thank you for your work!
I am really interested in this repo, but I run into a issue which I don't think can be addressed without help.
I ran the progress in the official knowLM container:

```
(zhixi) root@b2896f53f126:/app/KnowLM# CUDA_VISIBLE_DEVICES=0,1 python examples/generate_lora_web.py --base_model ./zjunlp_knowlm-13b-zhixi
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:50<00:00, 56.81s/it]
/app/KnowLM/examples/generate_lora_web.py:198: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  gr.inputs.Textbox(
/app/KnowLM/examples/generate_lora_web.py:198: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  gr.inputs.Textbox(
/app/KnowLM/examples/generate_lora_web.py:198: GradioDeprecationWarning: `numeric` parameter is deprecated, and it has no effect
  gr.inputs.Textbox(
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

Then I submit the instruction and inputs, and I got this:

`Segmentation fault (core dumped)`

I need to reboot the server to bring it back to normal. 
I also tried single GPU (RTX 4090), this time it report out of memory.
I also tried CUDA_VISIBLE_DEVICES=0,1 accelerate launch examples/generate_lora_web.py --base_model ./zjunlp_knowlm-13b-zhixi
and I got:

```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `2`
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Loading checkpoint shards:   0%|                                                                                                                      | 0/3 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 74 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 75) of binary: /opt/conda/envs/zhixi/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/zhixi/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/commands/launch.py", line 906, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/commands/launch.py", line 599, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
===================================================
examples/generate_lora_web.py FAILED
---------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
---------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-26_10:14:23
  host      : b2896f53f126
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 75)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 75
===================================================
```

As a beginner, I will appreciate it if you would response.

**Comment by MikeDean2367** [comment]
Hello, as this is a 13B model, it is recommended to use a GPU with more than 26GB of VRAM for inference. Since you are using a 24GB GPU, you will need at least two GPUs for multi-GPU inference. The inference command for multi-GPU setup is as follows: 
```
CUDA_VISIBLE_DEVICES=0,1 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi
```

**Comment by MikeDean2367** [comment]
Hello, multi-gpu inference requires using the first command. Regarding the error message, may I ask if your environment has been configured as required? You can first use the following command to check if it can run successfully:
```
CUDA_VISIBLE_DEVICES=0,1 python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_general_cases
```

**Comment by Hubotcoder** [comment]
> Hello, multi-gpu inference requires using the first command. Regarding the error message, may I ask if your environment has been configured as required? You can first use the following command to check if it can run successfully:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_general_cases
> ```

Thank you! I tried your command and I got this:

```
(zhixi) root@b2896f53f126:/app/KnowLM# CUDA_VISIBLE_DEVICES=0,1 python examples/generate_lora.py --base_model ./zjunlp_knowlm-13b-zhixi --run_general_cases
testing general abilities!
load_8bit=False
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:47<00:00, 55.90s/it]
{'num_beams': 3, 'temperature': 0.1, 'repetition_penalty': 1.3} 请你背诵《静夜思》
GenerationConfig {
  "num_beams": 3,
  "repetition_penalty": 1.3,
  "temperature": 0.1,
  "top_k": 40,
  "top_p": 0.75,
  "transformers_version": "4.28.1"
}

Traceback (most recent call last):
  File "/app/KnowLM/examples/generate_lora.py", line 216, in <module>
    fire.Fire(main)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/KnowLM/examples/generate_lora.py", line 207, in main
    print(evaluate(instruction, num_beams=cfg["num_beams"], temperature=cfg["temperature"], repetition_penalty=cfg["repetition_penalty"]))
  File "/app/KnowLM/examples/generate_lora.py", line 192, in evaluate
    generation_output = model.generate(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/generation/utils.py", line 1524, in generate
    return self.beam_search(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/generation/utils.py", line 2810, in beam_search
    outputs = self(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

**Comment by MikeDean2367** [comment]
Hello, I suspect it's an environmental issue. If there is sufficient memory, I suggest running it on the CPU first to see if it throws any errors. I'm also conducting tests concurrently.

**Comment by Hubotcoder** [comment]
> Hello, I suspect it's an environmental issue. If there is sufficient memory, I suggest running it on the CPU first to see if it throws any errors. I'm also conducting tests concurrently.

Thank you again for your response and efforts. 
FYI, I just pulled the official image and made no change to the environment except that I replaced the repo with the one of latest version to avoid loading lora.

**Comment by MikeDean2367** [comment]
@BeasterYong cc
Hello, I'm not in charge of the Docker image. It can run smoothly following the steps [here](https://github.com/zjunlp/KnowLM#manual-environment-configuration) and I just tested it again a moment ago.

**Comment by BeasterYong** [comment]
Sorry you had a problem using it! Have you installed nvidia-container-runtime? We will try to reproduce your problem and troubleshoot it soon.

**Comment by Hubotcoder** [comment]
> @BeasterYong cc Hello, I'm not in charge of the Docker image. It can run smoothly following the steps [here](https://github.com/zjunlp/KnowLM#manual-environment-configuration) and I just tested it again a moment ago.

Thank you.

**Comment by Hubotcoder** [comment]
> Sorry you had a problem using it! Have you installed nvidia-container-runtime? We will try to reproduce your problem and troubleshoot it soon.

Thank you, I'm looking forward to it!

**Comment by BeasterYong** [comment]
> > Sorry you had a problem using it! Have you installed nvidia-container-runtime? We will try to reproduce your problem and troubleshoot it soon.
> 
> Thank you, I'm looking forward to it!

Hello, thank you very much for your issue, we have also reproduced the same issue. We are trying to troubleshoot the cause, and we recommend you to prefer non-docker deployment of the model~

**Comment by BeasterYong** [comment]
This issue is caused by insufficient GPU memory resources, we recommend you to release the remaining processes that are consuming GPU resources, or use GPU resources with sufficient memory to deploy the model. It has been verified that the model reasoning runs normally after all the remaining processes have been cleared!

**Comment by BeasterYong** [comment]
This issue is caused by insufficient GPU memory resources, we recommend you to release the remaining processes that are consuming GPU resources, or use GPU resources with sufficient memory to deploy the model. It has been verified that the model runs normally after all the remaining processes have been cleared!

**Comment by Hubotcoder** [comment]
> This issue is caused by insufficient GPU memory resources, we recommend you to release the remaining processes that are consuming GPU resources, or use GPU resources with sufficient memory to deploy the model. It has been verified that the model runs normally after all the remaining processes have been cleared!

Thank you!
