### ISSUE TITLE
ValueError: Please specify the ZeRO optimization config in the DeepSpeed config.

### ISSUE THREAD

**Issue by zql022** [zjunlp/KnowLM#87]
DeepSpeed config里没有optimazation的键，而且测试添加上还是会报这个错，--deepspeed configs/config.json就是指定的deepspeed配置文件，但是为什么加上也没有用呢？
具体报错信息如下：
Traceback (most recent call last):
  File "/home/knowLM/pretrain/train.py", line 182, in <module>
    raise ValueError("Please specify the ZeRO optimization config in the DeepSpeed config.")
ValueError: Please specify the ZeRO optimization config in the DeepSpeed config.
    self.deepspeed_plugin = DeepSpeedPlugin(hf_ds_config=self.hf_deepspeed_config)
  File "<string>", line 14, in __init__
    train()
  File "/home/knowLM/pretrain/train.py", line 156, in train
  File "/home/anaconda3/envs/knowlm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py", line 601, in __post_init__
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 116, in __init__
    raise ValueError("Please specify the ZeRO optimization config in the DeepSpeed config.")
  File "/home/anaconda3/envs/knowlm/lib/python3.9/site-packages/transformers/training_args.py", line 1661, in __post_init__
ValueError: Please specify the ZeRO optimization config in the DeepSpeed config.
    self.deepspeed_plugin = DeepSpeedPlugin(hf_ds_config=self.hf_deepspeed_config)
求问解决方法

**Comment by MikeDean2367** [comment]
您好，请问：
1. 您的完整运行命令是什么？
2. 您的使用的环境是什么？

这对于复现这个问题至关重要

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by zql022** [comment]
并没有呢，有大佬帮忙指点一下

**Comment by zxlzr** [comment]
请提供：
您的完整运行命令是什么？
您的使用的环境是什么？

**Comment by zxlzr** [comment]
烦请您提供一下完整的命令，请问您的问题是否已解决？
