### ISSUE TITLE
ValueError: Can't read finetune/lora/templates/alpaca.json

### ISSUE THREAD

**Issue by fishfree** [zjunlp/KnowLM#96]
```
(knowlm) xiaomii@ubuntugpu:~/KnowLM$ CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi
Traceback (most recent call last):
  File "/home/data/xiaomii/KnowLM/examples/generate_lora_web.py", line 214, in <module>
    fire.Fire(main)
  File "/home/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/data/xiaomii/KnowLM/examples/generate_lora_web.py", line 39, in main
    prompter = Prompter(prompt_template)
  File "/home/data/xiaomii/KnowLM/examples/prompter.py", line 17, in __init__
    raise ValueError(f"Can't read {file_name}")
ValueError: Can't read finetune/lora/templates/alpaca.json
```

**Comment by Rolnand** [comment]
KnowLM/examples/generate_lora_web.py的第30行
prompt_template: str = "finetune/lora/templates/alpaca.json",  修改为
prompt_template: str = "finetune/lora/knowlm/templates/alpaca.json",

**Comment by zxlzr** [comment]
Have you solved your issue?

**Comment by fishfree** [comment]
@zxlzr I modified the code according to Rolnand's `[tip](https://github.com/zjunlp/KnowLM/issues/96#issuecomment-1791770835)`. However, **new error occured: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!**
```
(base) xiaomii@ubuntugpu:~/KnowLM$ CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi
Loading checkpoint shards: 100%|████████████████████████████████████████████████| 3/3 [00:25<00:00,  8.53s/it]
/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/inputs.py:30: UserWarning: `optional` parameter is deprecated, and it has no effect
  super().__init__(
/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/inputs.py:30: UserWarning: `numeric` parameter is deprecated, and it has no effect
  super().__init__(
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/interface.py", line 632, in fn
    async for output in iterator:
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/mnt/data/xiaomii/KnowLM/examples/generate_lora_web.py", line 157, in evaluate
    generation_output = model.generate(
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1611, in generate
    return self.beam_search(
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2982, in beam_search
    model_kwargs["past_key_values"] = self._reorder_cache(model_kwargs["past_key_values"], beam_idx)
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 762, in _reorder_cache
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
  File "/mnt/data/xiaomii/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 762, in <genexpr>
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```
Don't hurry to close an issue. :-) 别急着关闭issue哈~

**Comment by MikeDean2367** [comment]
您好，感谢您的反馈，我们已经支持了当一个模型被分布在多张卡是的推理问题，您可以在命令后面增加`--multi-gpu`即可，比如：
```shell
 CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi --multi_gpu
```

如有问题，请告知我 :)

**Comment by zxlzr** [comment]
Have you solved your issue?

**Comment by fishfree** [comment]
@zxlzr Sorry for reply late. Now there is no error output in the Linux conosle, but there is no output textbox in the web UI:
![image](https://github.com/zjunlp/KnowLM/assets/1741341/d13037e8-3e34-4acd-8f1e-037fa9c876d9)

**Comment by MikeDean2367** [comment]
Are you using the latest code? I can run the code correctly, you can try using the latest version of `gradio`.  Please let me know if there are still any issues :)

**Comment by fishfree** [comment]
@MikeDean2367 I git pull today, and change peft to peft==0.4.0 in the requirements.txt and re-run pip install -r requirements.txt
then run  `CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi --multi_gpu`

It shows error as below:
```
Traceback (most recent call last):
  File "/mnt/data/xiaomii/KnowLM/examples/generate_lora_web.py", line 225, in <module>
    fire.Fire(main)
  File "/mnt/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/data/xiaomii/KnowLM/examples/generate_lora_web.py", line 47, in main
    model, tokenizer = get_tokenizer_and_model(base_model=base_model, dtype="float16", allocate=allocate)
  File "/mnt/data/xiaomii/KnowLM/examples/multi_gpu_inference.py", line 46, in get_tokenizer_and_model
    max_memory = {i:f"{value}GiB" for i, value in enumerate(allocate)}
TypeError: 'NoneType' object is not iterable

```

**Comment by MikeDean2367** [comment]
Hi, I made a mistake and I have fixed it now :)

**Comment by fishfree** [comment]
Thank you so much for your diligence! New error as below:
```
 File "/mnt/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/accelerate/big_modeling.py", line 479, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/mnt/data/xiaomii/.conda/envs/knowlm/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 815, in load_checkpoint_in_model
    raise ValueError(
ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint, but got zjunlp/knowlm-13b-zhixi.
```

**Comment by fishfree** [comment]
@MikeDean2367 Would you pls help me check the issue as the commet above? Many thanks!

**Comment by MikeDean2367** [comment]
Can you provide more detailed information, including the full details of the command you ran and the complete error message?
